# Site not entirely customized using config
# Some meta tags in _includes/head.html and other file contents need manual edits
title: Leo Soares
email: leojrfs@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Create, invent, make...
baseurl: ""
url: "https://leojrfs.github.io"
twitter_username: leojrfs
github_username: leojrfs
disqus: leojrfs
google_analytics: UA-73731102-1 # get yours at https://analytics.google.com/analytics/web/

html_lang: en
permalink: /writing/:title/
exclude: [".ruby-version", "Gemfile", "Gemfile.lock", "wercker.yml"]

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed

# Plugins
gems:
  - jekyll-feed
